{
 "title": "New dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Gateway Request Rate (Traffic)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(spring_cloud_gateway_requests_seconds_count[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error / Fallback Rate (503)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(spring_cloud_gateway_requests_seconds_count{httpStatusCode=\"503\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Backend Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum(rate(spring_cloud_gateway_requests_seconds_bucket[1m])) by (le)\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Circuit Breaker State",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "resilience4j_circuitbreaker_state",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}